### ISSUE TITLE
Paste with mouse doesn't work on the text of the watermark

### ISSUE THREAD

**Issue by ghost** [marioestrada/jQuery-Watermark#6]
If we try to past text in an input text with the mouse (rigth click) it doesn't work if I click on the text of the watermark but work fine near the text.

**Comment by marioestrada** [comment]
I image this only happens on Internet Explorer, maybe versions 8 and under. If that's the case there isn't an easy fix, so I may not fix it.

**Comment by ghost** [comment]
This bug happend on IE 7,8 and 9. All my tests are done on the demo site

**Comment by ChrisTorng** [comment]
I found this issue in IE10, and two more issues.
One is the title's tooltip won't show when mouse pointer on the watermark.
The other is if the title text is too long, then it will flow down and out of the textbox.
I have an idea, doesn't know if it works.
If you let the watermark label under the textbox, as big as textbox, transparent the textbox's background, and set the watermark label's background as the textbox's original background. Then maybe it can solve these issues...

**Comment by marioestrada** [comment]
The fix you are detailing can be achieved manually with custom CSS.

The html format goes like this:

``` HTML
<span class="watermark_container">
<span class="watermark">Placeholder</span>
<input type="text" />
</span>
```

I wouldn't implement it as the standard because every textbox will not be styled the same and it would be very complicated to copy every style the input box have and have it fit flawlessly behind the textbox.

I would recommend that if anyone is having a similar issue to implement you proposed fix and style it to their needs.
